# Site settings
title: WOW air
client:
  name: WOW air
  link: "#client-name"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Iceland packs an astonishing amount of natural beauty into its roughly 40,000 square miles. The starting price to Iceland is $99.99 one-way and is available from many US departure cities*

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/wow-air" # the subpath of your site, e.g. /blog/
img:     "/wow-air/_assets/img"
css:     "/wow-air/_assets/css"
js:      "/wow-air/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed