# Site settings
title: WOW air
client:
  name: WOW air
  link: "https://wowair.us/flights/our-destinations/reykjavik/?utm_source=secretescapes.com&utm_medium=blog&utm_campaign=secretescapes.com_14june2018"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Fly WOW air to Reykjavik from 12 cities across the U.S., and discover Iceland for yourself. Become the hero of your own unwritten epic or saga as you become acquainted with the colorful capital city, then head into the country and experience the legendary landscape firsthand.


# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/wow-air" # the subpath of your site, e.g. /blog/
img:     "/wow-air/_assets/img"
css:     "/wow-air/_assets/css"
js:      "/wow-air/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed